[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
]


ffi = true
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./script/" },
    { access = "read", path = "./broadcast/" },
]


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
